- name: Provision EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    keypair: "demoKeyPair2"
    instance_type: "t2.micro"
    ami_id: "ami-0440d3b780d96b29d"
    region: "us-east-1"
    security_group: "launch-wizard-44"
    ec2_instance_name: "ansible_instance"
    ssh_public_key_file: "~/.ssh/id_rsa.pub"

  tasks:
    - name: start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "public-compute-instance"
        key_name: "{{ keypair }}"
        vpc_subnet_id: subnet-0d0d18e647f821bcf
        instance_type: "{{ instance_type }}"
        security_group: default
        network:
          assign_public_ip: true
        image_id: "{{ ami_id }}"
        user_data: |
          #!/bin/bash
          mkdir -p /home/ec2-user/.ssh
          echo "{{ lookup('file', ssh_public_key_file) }}" >> /home/ec2-user/.ssh/authorized_keys
          chown -R ec2-user:ec2-user /home/ec2-user/.ssh
          chmod 700 /home/ec2-user/.ssh
          chmod 600 /home/ec2-user/.ssh/authorized_keys
        tags:
          Environment: Testing
      register: ec2_instance

    - name: Print IP address of the newly created EC2 instance
      debug:
        msg: "EC2 instance created with IP address {{ item.public_ip }}"
      with_items: "{{ ec2_instance.instances }}"
